apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: frankenphp
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: symfony-frankenphp
  policy:
    semver:
      range: "latest"