apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: frankenphp
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: symfony-frankenphp
  git:
    checkout:
      ref:
        branch: main
    commit:
      authorName: fluxcd
      authorEmail: fluxcdbot@users.noreply.github.com
    push:
      branch: main
  update:
    strategy: Setters