apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: frankenphp
  namespace: flux-system
spec:
  image: devho/franken-php
  interval: 1m0s
  secretRef:
    name: regsecret
  