apiVersion: v1
kind: Service
metadata:
  name: frankenphp
spec:
  type: ClusterIP
  selector:
    app: frankenphp
  ports:
  # - name: https
  #   protocol: TCP
  #   port: 443
  #   targetPort: 443
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
    
    
