apiVersion: batch/v1
kind: Job
metadata:
  name: composer
spec:
  template:
    spec:
      containers:
      - name: composer
        image: composer/composer:2.2.26
        command: ["composer",  "install", "--no-dev", "--optimize-autoloader"]
      
      restartPolicy: Never

