name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ðŸš€
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: echo github.ref
        run: echo ${{github.ref}}
      - run: echo "ðŸ This job's status is ${{ job.status }}."
    
      - name: Start docker
        run: docker compose -f compose.yml up -d

      # - name: Check the deployed service URL
      #   uses: jtalk/url-health-check-action@v4
      #   with:
      #     # Check the following URLs one by one sequentially
      #     url: http://localhost:8080/healthz
      #     # Follow redirects, or just report success on 3xx status codes
      #     follow-redirect: false # Optional, defaults to "false"
      #     # Fail this action after this many failed attempts
      #     max-attempts: 3 # Optional, defaults to 1
      #     # Delay between retries
      #     retry-delay: 5s # Optional, only applicable to max-attempts > 1
      #     # Retry all errors, including 404. This option might trigger curl upgrade.
      #     retry-all: true # Optional, defaults to "false"
      - uses: "ramsey/composer-install@v3"
        with:
          composer-options: "--no-interaction --no-progress"
      # - name: Install Composer dependencies
      #   run: docker compose -f compose.yml run --rm php composer install --no-interaction --no-progress

      - name: Test migration
        run: docker compose -f compose.yml exec -T php php bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration

      - name: Validate Doctrine schema
        run: docker compose -f compose.yml exec -T php php bin/console doctrine:schema:validate

      # - name: Reload Hasura metadata
      #   run: docker compose -f compose.yml exec -T php php bin/console hasura:metadata:reload

      # - name: Test apply Hasura metadata
      #   run: docker compose -f compose.yml exec -T php php bin/console hasura:metadata:apply